version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "1434:1433"
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5100:5100"
    environment:
      - APEX_apiAddress=http://*:5100
      - "APEX_apexConnectionString=Data Source=db;Initial Catalog=Apex;User Id=SA;Password=GR3@Tpassword;"
      - APEX_webAddress=http://localhost:8080
      - APEX_logsDir=
      - APEX_cookieDomain=localhost
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"