version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "1434:1433"
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5100:5100"
    environment:
      - APEX_Api__apiAddress=http://*:5100
      - APEX_Api__cookieDomain=localhost
      - APEX_Api__webAddress=http://localhost:8080
      - APEX_Log__directory=
      - "APEX_Sql__connectionString=Data Source=db;Initial Catalog=Apex;User Id=SA;Password=GR3@Tpassword;"
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"