name: API Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup ECR
      run: $( aws ecr get-login --no-include-email )
      
    - name: Build image
      run: docker build -t apex_api-prod -f api/DockerFile .
      
    - name: Tag image
      run: docker tag apex_api-prod ${{ secrets.AWS_API_ECR_REPOSITORY }}

    - name: Push image
      run: docker push ${{ secrets.AWS_API_ECR_REPOSITORY }}
