name: SQL Migration

on:
  push:
    branches: [ master ]
    paths:
      - api/api.db.model/**/*
      - .github/workflows/sql-migration.yml

env:
  APEX_Sql__ConnectionString: ${{ secrets.SQL_CONNECTION_STRING }}

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install EF Core tools
      run: |
        dotnet tool install --global dotnet-ef --version 3.1.0
        dotnet tool restore

    - name: Migrate
      run: dotnet ef database update
      working-directory: ./api/api.db.model
